### ISSUE TITLE
Doesn't work in Windows 10 64-bit

### ISSUE THREAD

**Issue by thjwong** [vaskovsky/notify-send#2]
Hi Alexey,
I don't have time to compile (I may use CodeBlocks for this).
But it doesn't work for me in Windows 10 (64-bit).

Please take a look when you have time.
Thanks for creating this! :)

**Comment by vaskovsky** [comment]
The new version (2.1.0) has been released.

[Download precompiled binary](http://vaskovsky.net/notify-send/notify-send.zip)

If the problem has not been solved send me `Debug.log` (see [Troubleshooting](http://vaskovsky.net/notify-send/troubleshooting.html))
