### ISSUE TITLE
Update .NET requirement to v4 or later

### ISSUE THREAD

**Issue by carlosvsilva** [vaskovsky/notify-send#5]
Hi, on Windows 10 I'm prompted to install .NET2/3 which are really old by now. Can you please update the dependency to .NET 4 or later? Thanks

**Comment by vaskovsky** [comment]
The project has been rebuilt under .NET Framework 4

[Download notify-send v3.0.0](https://github.com/vaskovsky/notify-send/releases/download/v3.0.0/notify-send.exe.3.0.0.zip)

**Comment by carlosvsilva** [comment]
Thanks! Best regards.
