### ISSUE TITLE
Can't set title and notification disappears from Win10 notification center

### ISSUE THREAD

**Issue by carlosvsilva** [vaskovsky/notify-send#6]
Hi!
Apparently setting the title with -a "title" doesn't seem to have any effect on the notification as it always displays the title 'notify-send.exe'. Also the notification is disappearing from Notification Center, not sticking around until dismissed like it should.

`notify-send.exe --debug -i error -a "Teste" "Novidades" "Hello World"`
2021-02-12 09:52:54 NotifySend.Init
        AppName: Teste
        Title: Novidades
        Message: Hello World
        Icon: Error
        Timeout: 5000
2021-02-12 09:52:54 NotifySend.Show
2021-02-12 09:53:01 NotifySend.Hide
2021-02-12 09:53:01 NotifySend.Exit

**Comment by vaskovsky** [comment]
If you need to change the title "notify-send.exe", you should rename the executable file. 

`-a APPNAME`: sets the ToolTip text displayed when the mouse pointer rests on a notification area icon.

![Screenshot](https://user-images.githubusercontent.com/12381353/107972928-9bea5c00-6fc5-11eb-9d06-cee43c9d8d1a.png)

`-t TIMEOUT` is deprecated as of Windows Vista. Notification display times are now based on system accessibility settings.
The notification disappears from the Notification Center when the user closes it, or closes the Notification Center, or clicks on the notification, or clicks the notify-send icon.

Version 3.0.1 has been released. It fixes some bugs: [CHANGELOG](https://github.com/vaskovsky/notify-send/blob/master/CHANGELOG.md)

[Download](https://github.com/vaskovsky/notify-send/releases/download/v3.0.1/notify-send.exe.3.0.1.zip)

**Comment by vaskovsky** [comment]
The documentation has been updated: http://vaskovsky.net/notify-send.html
