### ISSUE TITLE
Multiple instances of notify-send launched with the same arguments keep running forever with no way to dismiss

### ISSUE THREAD

**Issue by D3viantS4ge** [vaskovsky/notify-send#7]
When running notify-send with the same arguments multiple times in a row, dismissing the notification causes only one instance to quit. The rest of the instances keep waiting forever even though there are no notifications left to dismiss.

**Comment by vaskovsky** [comment]
Try the new version: [4.0.0](https://github.com/vaskovsky/notify-send/releases/download/v4.0.0/notify-send.exe.4.0.0.zip)

**Comment by D3viantS4ge** [comment]
Cool, thanks!
